owner: DouglasNeuroInformatics
repo: upptime

sites:
  - name: DNP Remote Access Gateway
    check: "tcp-ping"
    url: $GATEWAY
    port: $GATEWAY_PORT
  - name: Open Data Capture (front-end)
    url: https://demo.opendatacapture.org/auth/login
  - name: Open Data Capture (back-end)
    url: https://demo.opendatacapture.org/api
  - name: Mouse Open Data Capture
    url: https://mouseodc.douglasneuroinformatics.ca/auth/login
  - name: Data Bank (front-end)
    url: https://databank.douglasneuroinformatics.ca/auth/login
  - name: Data Bank (back-end)
    url: https://databank.douglasneuroinformatics.ca/api
  - name: Mattermost
    url: https://chat.douglasneuroinformatics.ca
  - name: Tickets
    url: https://support.douglasneuroinformatics.ca
  - name: Neurobagel (Alliance FRQS)
    url: https://neurobagel-alliancefrqs.douglasneuroinformatics.ca
  - name: DNP's LimeSurvey
    url: https://survey.douglasneuroinformatics.ca/
  - name: MCMP's Omero Server
    url: https://omero.mcmpdouglas.ca/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.douglasneuroinformatics.ca
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/84101648?s=48&v=4
  name: Douglas Neuroinformatics Platform's Status Page
  introTitle: "** DNP status ***"
  introMessage: "Below is the status of the services we offer and monitor for other groups:"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
